version: '3.8'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-passworddb}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
    # - db-data:/var/lib/postgresql/data:rw
    # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - "5432"
    networks:
      - fast_track_network
  ###< doctrine/doctrine-bundle ###

  php-fpm:
    container_name: php-fpm
    build:
      context: php
    depends_on:
      - database
    volumes:
      - ./../:/var/www
    expose:
      - 9000
    networks:
      - fast_track_network

  nginx:
    container_name: nginx
    build:
      context: nginx
    volumes:
      - ./../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
    networks:
      - fast_track_network

networks:
  fast_track_network: